apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8081       # Service port (inside cluster)
      targetPort: 8081 # Pod container port
      nodePort: 30007  # Exposed NodePort (optional)
